---
functional:
  - Пользователь может просматривать каталог товаров с постраничным выводом.
  - Пользователь может фильтровать товары по категориям, цене, рейтингу и другим параметрам.
  - Пользователь может искать товары по ключевому слову.
  - Пользователь может просматривать детальную информацию о товаре (название, рейтинг, цена со скидкой и без).
  - Пользователь может добавлять товары в корзину.
  - Пользователь может просматривать содержимое корзины.
  - Пользователь может удалять товары из корзины.
  - Пользователь может оформлять заказ с переходом на страницу оплаты.
  - Корзина должна сохраняться в сессии браузера.

non-functional:
  - Сайт должен быть адаптивным и удобным для использования на мобильных устройствах.
  - Сайт должен быть SPA-приложением (без перезагрузки страницы).
  - Сайт должен быть оптимизирован для высокой скорости работы.
  - Сайт должен быть безопасным и защищать данные пользователя.
  - Сайт должен быть совместим с последними версиями популярных браузеров.
  - Сайт должен быть способен обрабатывать большое количество трафика.
  - Сайт должен быть доступен на различных устройствах (десктопы, планшеты, мобильные).

implicit:
  - Сайт должен иметь интуитивно понятный интерфейс для пользователя.
  - Сайт должен поддерживать кэширование данных для повышения производительности.
  - Сайт должен иметь механизм обработки ошибок (например, при недоступности сервера или некорректных данных).
  - Сайт должен быть доступен для пользователей с ограниченными возможностями (например, поддержка screen readers).
  - Сайт должен иметь возможность масштабирования для будущих обновлений и добавления новых функций.
  - Сайт должен иметь систему логирования для отслеживания ошибок и анализа пользовательского поведения.
  - Сайт должен поддерживать мультиязычность (если предполагается международная аудитория).
